{
 "title": "Kubernetes / Views / Nodes List",
 "description": "This is a 'Nodes List View' dashboard for your Kubernetes cluster(s). Tested with K3s, Rke2 and OpenShift.",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster_label",
    "label": "Cluster label",
    "query": "prometheus_cluster, cluster, kubernetes_cluster, k8s_cluster"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info,$cluster_label)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_disk_info{$cluster_label=~\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Instance",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$instance(:[0-9]+)?\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=~\"$instance(:[0-9]+)?\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance(:[0-9]+)?\", \"$cluster_label\"=\"$cluster\"} - node_memory_MemAvailable_bytes{instance=~\"$instance(:[0-9]+)?\", \"$cluster_label\"=\"$cluster\"}) / sum(node_memory_MemTotal_bytes{instance=~\"$instance(:[0-9]+)?\", \"$cluster_label\"=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$instance(:[0-9]+)?\", \"$cluster_label\"=\"$cluster\"} - node_boot_time_seconds{instance=~\"$instance(:[0-9]+)?\", \"$cluster_label\"=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$instance(:[0-9]+)?\", \"$cluster_label\"=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_info{host_ip=~\"$instance(:[0-9]+)?\", \"$cluster_label\"=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Network usage (bit/s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$instance(:[0-9]+)?\", \"$cluster_label\"=\"$cluster\"}[$__rate_interval]))*8",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$instance(:[0-9]+)?\", \"$cluster_label\"=\"$cluster\"}[$__rate_interval]))*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_cpu_info{instance=~\"$instance(:[0-9]+)?\", \"$cluster_label\"=\"$cluster\"})"
    },
    {
     "expr": "machine_cpu_cores{instance=~\"$instance(:[0-9]+)?\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance(:[0-9]+)?\", \"$cluster_label\"=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}